# Test and Production docker-compose file.

version: '2'
services:
  web:
    container_name: digital_app-template
    build: . # Can't be below this since we have to add files in public/
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
    links:
     - db
    environment:
     - DRUPAL_INSTALL=TRUE
     - HTPASSWD_USER=${HTPASSWD_USER}
     - HTPASSWD_PASSWORD=${HTPASSWD_PASSWORD}
  db:
    container_name: digital_app-template_db
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=docker
     - MYSQL_DATABASE=drupal
     - MYSQL_USER=drupal
     - MYSQL_PASSWORD=drupalpw
    volumes:
     - data:/var/lib/mysql
volumes:
  data: {}
